// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC3Mp-EVjMlpGBa-uAAqJFiIvbdlxVOL0',
    appId: '1:854765499321:web:c37b40ffea24db34f33c68',
    messagingSenderId: '854765499321',
    projectId: 'mealmate-9a8c5',
    authDomain: 'mealmate-9a8c5.firebaseapp.com',
    storageBucket: 'mealmate-9a8c5.firebasestorage.app',
    measurementId: 'G-3N8GNDM2CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApZBsoXY1WzBH3d_xruY48VIzCjuD__b8',
    appId: '1:854765499321:android:3854d4537b480029f33c68',
    messagingSenderId: '854765499321',
    projectId: 'mealmate-9a8c5',
    storageBucket: 'mealmate-9a8c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9D0Vq7mctXx2FksEkaLfTbQXSXlLs2vo',
    appId: '1:854765499321:ios:a4aaa0efb62f8739f33c68',
    messagingSenderId: '854765499321',
    projectId: 'mealmate-9a8c5',
    storageBucket: 'mealmate-9a8c5.firebasestorage.app',
    iosBundleId: 'com.example.mealmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9D0Vq7mctXx2FksEkaLfTbQXSXlLs2vo',
    appId: '1:854765499321:ios:a4aaa0efb62f8739f33c68',
    messagingSenderId: '854765499321',
    projectId: 'mealmate-9a8c5',
    storageBucket: 'mealmate-9a8c5.firebasestorage.app',
    iosBundleId: 'com.example.mealmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC3Mp-EVjMlpGBa-uAAqJFiIvbdlxVOL0',
    appId: '1:854765499321:web:25984210e8a28a61f33c68',
    messagingSenderId: '854765499321',
    projectId: 'mealmate-9a8c5',
    authDomain: 'mealmate-9a8c5.firebaseapp.com',
    storageBucket: 'mealmate-9a8c5.firebasestorage.app',
    measurementId: 'G-WQ5WJGX7XC',
  );
}
